name: vorkybot
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  teledart: ^0.6.1
  drift: ^2.16.0
  sqlite3: any
  path: any

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  drift_dev: ^2.16.0
  build_runner: any
